version: '3'

services:
  konrad-docker-compose-container:
    container_name: konrad-docker-compose-container
    image: konrad-docker-image:1
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"